name: Auto Update Orchestrator

on:
  schedule:
    # Tuesday 6pm ET (22:00 UTC, accounting for EST/EDT)
    - cron: '0 22 * * 2'
  workflow_dispatch: {} # Manual trigger for testing

jobs:
  update-docs:
    name: Update Documentation
    permissions:
      contents: write
    uses: ./.github/workflows/auto-update-docs.yml
    
  update-index:
    name: Update Search Index
    needs: update-docs
    permissions:
      contents: write
    uses: ./.github/workflows/auto-update-index.yml
    
  # publish:
  #   name: Publish Image
  #   needs: update-index
  #   permissions:
  #     contents: read
  #     attestations: write
  #     id-token: write
  #   uses: ./.github/workflows/auto-update-publish.yml
